### ISSUE TITLE
failed to build boost-1.60

### ISSUE THREAD

**Issue by Cynede** [vayerx/vayerx-gentoo#1]
ls: cannot access libboost_test_exec_monitor.a.1.60.0: No such file or directory
ls: cannot access libboost_exception.a.1.60.0: No such file or directory
rm: cannot remove ‘/var/tmp/portage/dev-libs/boost-1.60.0-r666/image//usr/include/boost-1.60/python*’: No such file or directory

gcc 5.3.0

**Comment by vayerx** [comment]
I couldn't reproduce it on my machine neither with gcc 4.9 nor with 5.3.
What USE-flags are you using to build boost?
Are there any other errors in build log? Could you please paste full build log somewhere?

```
equery f boost:1.60 | grep test_exec_monitor.a
/usr/lib32/libboost_test_exec_monitor.a.1.60
/usr/lib32/libboost_test_exec_monitor.a.1.60.0
/usr/lib64/libboost_test_exec_monitor.a.1.60
/usr/lib64/libboost_test_exec_monitor.a.1.60.0
```

**Comment by Cynede** [comment]
@vayerx sorry but can't currently provide more details, I will reopen issue when I will be able to gather
