### ISSUE TITLE
Source files's location changed

### ISSUE THREAD

**Issue by rebeka-catalina** [vayerx/vayerx-gentoo#2]
Url of aptana 3.6.1.zip changed from

https://github.com/aptana/studio3/releases/download/v3.6.1/Aptana_Studio_3_Setup_Linux_x86_64_3.6.1.zip

to
https://github.com/aptana/studio3/archive/v3.6.1.zip

I don't know, how I could handle things like this - that's why I ask you to change the ebuild.
I hope this is ok?

**Comment by rebeka-catalina** [comment]
> Closed #2 via ec9f67f99ddd9d0a910928a57b3527a3a376aefa.

Thank you :-)

**Comment by vayerx** [comment]
You are welcome :-)
And thank you for report.
